services:
  - type: web
    name: tiffin-service
    runtime: python
    buildCommand: pip install django
    startCommand: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
